# Generated by Django 4.2.1 on 2023-05-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.CharField(max_length=10)),
                ('lte_exists', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
