# Generated by Django 4.2.1 on 2023-05-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_image_alter_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
