# Generated by Django 4.2.1 on 2023-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_id_alter_phone_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='URL товара'),
        ),
    ]
