# Generated by Django 4.2.1 on 2023-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='URL товара'),
        ),
    ]
